#!/usr/bin/env node
/**
 * NOON Word Square Generator
 * Generates 4×4 word squares where rows === columns (symmetric matrix).
 * Constraint: SOLUTION[i][j] === SOLUTION[j][i] for all i,j.
 */
import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));

// ── Word list (common 4-letter English words) ──────────────────────────────
const WORDS_RAW = `
ABLE ACHE ACID AGED AIRY ALAS ALMS ALSO ALTO AMOK ANEW ANTE APEX ARCH AREA
ARMS ARMY ATOP AWAY AWED AXES AXIS
BABE BACK BAIL BAIT BALE BALM BALL BAND BANE BANK BARE BARN BASE BASH BASS
BATH BEAD BEAK BEAR BEAT BEEF BEEN BELL BELT BEST BIDE BILL BITE BLEW BLOW
BLOT BLUE BLUR BOAR BODY BOLD BOLT BOND BONE BOOK BOOM BOOT BORE BORN BOTH
BRAG BRAT BREW BROW BULL BUMP BURN BUSY
CAFE CAGE CAKE CALF CALL CALM CAME CANE CARD CARE CARP CART CASE CASH CAST
CAVE CELL CHEF CHIP CITY CLAM CLAP CLAY CLOT CLUE CLUB COAL COAT CODE COIL
COLD COME CONE COOK COOL COPE COPY CORD CORE CORN COST COUP CREW CROP CROW
CUBE CURE CURL CUTE
DAMP DARE DARK DATA DATE DAYS DEAD DEAF DEAL DEAN DEAR DEBT DECK DEED DEEP
DENT DENY DESK DIAL DIET DICE DIKE DILL DIME DINE DIRT DISC DISH DISK DIVE
DOCK DOLE DOME DONE DOOM DOOR DOSE DOTE DOUR DOWN DRAB DRAW DRIP DROP DRUG
DRUM DUAL DUEL DUMP DUSK DUST
EACH EARN EASE EAST EDGE ELSE EMIT ENVY EPIC EVEN EVER EVIL EXAM
FACE FACT FADE FAIL FAIR FAKE FALL FAME FANG FARM FAST FATE FAWN FEAR FEAT
FEEL FEET FELL FEND FERN FILE FILL FILM FIND FINE FIRE FIRM FISH FIST FLAT
FLAW FLEA FLEE FLEW FLEX FLIT FLOW FOAM FOLD FOLK FOND FONT FOOD FOOL FORE
FORK FORM FORT FOUL FOUR FREE FROG FUEL FULL FUND FURY
GALE GAME GANG GAVE GAZE GEAR GENE GIFT GIRL GIVE GLAD GLEE GLOW GLUE GOAL
GOLD GOLF GOOD GORE GOWN GRAB GRAM GRAY GREW GRIN GRIP GROW GULF GUST
HACK HAIL HALF HALL HALT HAND HANG HARD HARM HARK HATE HAVE HAZE HEAD HEAL
HEAP HEAR HEAT HEED HEEL HELD HELM HELP HERB HERD HERE HERO HIGH HIKE HILL
HINT HIRE HOLD HOLE HOME HOOD HOOK HOPE HOSE HOST HOUR HOWL HULL HUNG HUNT HURT
ICON IDEA IDLE INCH INTO IRON ITEM
JAIL JEST JOLT JUMP JURY JUST
KEEN KEEP KICK KILL KIND KING KISS KNEW KNOW
LACK LAKE LAMP LAND LANE LARD LARK LASH LAST LATE LAVE LAWN LAZE LEAD LEAF
LEAN LEAP LEAK LEND LENS LESS LEVY LIFE LIFT LIKE LIME LIMB LINE LINK LIST
LIVE LOAD LOAN LOCK LONE LONG LOOK LOOP LORD LOSE LOSS LOST LOUD LOVE LUCK LULL LURE
MACE MADE MAIL MAIN MAKE MALL MARE MARK MART MASK MASS MAST MATE MAZE MEAL
MEAN MEAT MEET MELD MELT MEND MENU MEMO MERE MESH MILD MILE MILL MIND MINE
MINT MOCK MODE MOOD MORE MOST MOVE MUCH MULL MUSE MUST MYTH
NAME NAVY NEAR NEAT NECK NEED NEWS NEXT NICE NINE NODE NONE NOON NORM NOTE NOUN
OATH ODDS ONCE ONLY OPEN ORAL OVER
PACE PAGE PAIR PALE PALM PARK PART PASS PAST PATH PAVE PEAK PEEL PEER PICK
PILL PINE PINK PIPE PLAN PLAY PLEA PLOT PLUS POET POLE POLL POND POOL POOR
PORE PORT POSE POST POUR PRAY PREY PROD PULL PUMP PURE PUSH
RACE RACK RAGE RAIN RAMP RANG RANK RARE RASP RATE RAVE READ REAL REAP REAR
REED REEL RELY REND RENT RICE RICH RIDE RING RIOT RISE RISK ROAD ROAM ROAR
ROBE ROLE ROLL ROMP ROOF ROOM ROOT ROPE ROSE RULE RUSH RUST
SACK SAFE SAGA SAGE SAIL SAKE SALE SALT SAME SAND SANE SAVE SEAL SEAM SEAT
SEED SEEK SEEM SEEN SELF SELL SEND SHED SHIN SHIP SHOE SHOT SHOW SIDE SIGN
SILK SING SINK SIZE SKIN SKIP SLAM SLAP SLIP SLOW SNOW SOAP SOFT SOIL SOLD
SOLE SOME SONG SOON SORE SOUL SOUP SPAN SPIN SPOT SPUR STAR STAY STEM STEP
STIR STOP STUB STUD SUCH SUIT SURE
TAIL TALE TALL TANK TAPE TASK TELL TEND TENT TERM TEST THAN THAT THEM THEN
THIN THIS TIDE TIER TILL TIME TINY TIRE TOLD TOLL TONE TOOL TORN TOUR TOWN
TREE TRIM TRIP TRUE TUBE TUNE TURN TYPE
UGLY UNIT URGE USED USER
VALE VAST VEIL VEND VENT VERB VIEW VILE VINE VISE VOID
WADE WAKE WALK WALL WARD WARM WARN WARY WAVE WEAK WEAR WEED WELL WEND WENT
WERE WEST WIDE WILD WILL WIND WINE WING WIRE WISE WISH WITH WOLF WOOD WORD
WORE WORK WORM WORN WRAP
YARD YEAR YELL
ZEAL ZEST ZERO ZINC ZONE
ABLY ACME ADDS AFAR AGAR AGES AHEM AIDS AIMS AIRS ALOE ALMS ALPS AMOK AMPS
ANAL ANEW ANTE APEX AQUA ARCS ARTY ATOP AWED AXES AXIS
BAAS BABE BAIL BALE BALM BARD BASH BASS BEAD BEAK BEEF BIDE BLEW BLOT BOAR
BOLD BOLT BOND BONE BOOM BOOT BORE BRAG BRAT BREW BROW BUNK BUOY BURR
CABS CAFE CALF CANE CARP CEDE CHOP CHOW CHUM CITE CLAD CLAN CLOT CLUE COZY
CRAM CUFF CURB
DAIS DALE DAZE DEEM DELI DELL DISC DISH DOCK DOLE DOLT DOTE DOUR DRAB DRIP
EBON EDGY EGOS ELSE EMIT ENVY EPIC
FAWN FEAT FEND FERN FEUD FIGS FLAT FLEA FLEX FLIT FLOP FOND FORE FOWL FRAY
FRET FROG FUME FUND FURY
GALE GALL GASH GASP GAWK GAZE GLEE GLEN GLOB GOAD GOOF GORE GORY
HANK HARE HARK HASH HAUL HEED HEFT HIKE HIVE HONE HONK HOOP HOSE HOWL
LACE LARD LARK LASH LAVE LAWN LAZE LEAK LEER LEND LEVY LIMB LIMP LOIN LOOT
LORE LOUT LULL LUNG
MACE MARE MARL MART MELD MEND MENU MILD MOAT MOCK MOLT MONK MOON MOPE MOSS
MULL MURK MYTH
NARC NAVE NECK NEWT NIGH NODS
OAFS OAKS OARS OATS ODES OILS OMEN OMIT ONTO ORBS OVAL OVEN
PACT PAPA PARD PAVE PEEP PIED PINT PITH PITY PODS POKE PONY POSH PROD PROP PUNY
RAGS RAID RAMP RANG RAPT RAVE REAP REND REPO RIFE RIME RIND RINK RIPE ROMP
ROVE RUIN RUTS
SACK SAGA SASH SCAM SCAN SCAR SHED SHIN SLAB SLAP SLUG SLUR SMUG SNAG SNAP
SNOB SNUG SOAK SPED STEW STUB SUDS SWAP SWAT SWAY
TACK TAME TANG TAUT TEAK TEEM TILT TINT TOIL TOME TONG TOSS TROD TUCK TUFT
TURF TWIG TWIN TYPO
ULNA UNDO UNTO
VALE VANE VEIL VEND VENT VERB VILE VISE
WADE WAIF WAIT WAIL WELT WEND WHET WICK WILE WISP WRIT
YOGA YORE YOWL
ZEAL ZEST ZINC
ACHE ACRE ACTS ADDS AFAR AIDE AIMS AIRY AKIN ALOE ALSO ALTO AMEN AMID AMOK
ANTI ARCH AVID AVOW AWED AWRY AXLE
BAIT BALE BALK BALM BAND BANE BANG BARD BASK BASS BATH BAWL BEAK BEAM BEEN
BEES BELT BENE BENT BIER BILE BILK BIND BING BIOG BLAB BLAH BLAB BLIP BLOB
BLOC BLOT BLOW BOAR BORG BORE BORN BOSH BROW BUCK BUNG BUNK BURL BURR BUTT
CAGE CAPE CAPO CARD CASK CAST CAVE CITE CLAM CLAP CLOD COAL COAX COIL COZY
CRAM CUFF CURB CYAN
DASH DAZE DEFT DELL DIKE DILL DINT DIRE DISK DIVA DOER DORY DOTE DOUR DRUB
DUNK DUPE DUSK
EARL EARN EONS EPIC ERGO ERST EXAM EXPO EYRE
FAIN FAZE FEAT FEUD FIFE FISC FIZZ FLAB FLAT FLAY FLEX FLIT FLOE FLOP FLUB
FLUE FLUX FOGY FOLD FOND FONT FORE FOWL FRAY FRET FRIG FROC FROM FRUG FUME
GALE GALL GASH GASP GAWK GEEK GIST GLEE GLEN GLIB GLOB GOAD GOOF GORY GUST
HALE HARK HELM HEME HIGH HOCK HOIK HOLY HONE HONK HOOP HOSE HULA HULL HUMP HUNG
ICES ICON IDLE IFFY INKS ISLE ITCH
JABS JACK JADE JAPE JEER JEST JIBE JINX JOWL JUGS JUNK JURY
KELP KILT KNIT KNOB KNOT KYLE
LACE LACY LAIN LAKE LAMB LAME LAMP LAUD LEIS LIEN LIEU LIMP LODE LOFT LOGO
LOON LORE LOUR LOUT LUFF LUNG
MACE MAID MAIM MALL MANX MARL MART MAUL MAZE MEOW MESA MICA MIDI MIFF MILD
MILL MINK MOAT MOCK MOLD MOLT MONK MOOR MOSS MOTE MULL MURK MUTT MYTH
NAIF NARC NAVE NIGH NILL NITS NOEL NUKE
OAFS OAKS OATS OBOE ODES OILS OMEN OMIT ONTO ORBS OVAL OVEN OVUM
PABK PACT PAPA PARD PARS PAVE PAWL PAWN PEEP PELF PIED PIGS PINE PINT PIRN
PITH PITY PIXY PLAN PLEA PLOP PLOY PLUG PODS POKE PONY POPS POSE POSH PROD
PROM PROP PROS PROW PUBS PUNY PUPA PYRE
QUAY QUIT
RAGS RAID RAPT RASP RAVE RAZE REAP REDO REFS REPO RIFE RIME RIND RINK RIPE
RODE ROMP ROOK ROVE RUED RUFF RUIN RUSE RUTS
SACK SAGA SASH SASS SCAM SCAN SCAR SEEP SLAB SLAP SLAT SLOP SLUG SLUR SMUG
SNAG SNAP SNOB SNUG SOAK SPED SPEW SPRY STEW STUB STUD STUN SUDS SWAM SWAP
SWAT SWAY SWUM
TACK TALC TAMP TANG TARN TAUT TEAK TEEM TILT TINT TOIL TOME TONG TOPS TORE
TOSS TROD TROT TUCK TUFT TURF TWIG TWIN TYPO
ULNA UNDO UNTO
VALE VANE VEIL VEND VERT VEST VIBE VIDE VIED VIES VILE VINE VISE VITA
WADE WAIF WAIT WAIL WARD WELT WEND WHET WHIP WHIZ WICK WILE WISP WRIT WYES
YOGA YORE YOWL
ZEAL ZEST ZINC ZOOM
`.trim();

const WORDS = [...new Set(
  WORDS_RAW.split(/\s+/).map(w => w.trim()).filter(w => /^[A-Z]{4}$/.test(w))
)].sort();

console.log(`Word list: ${WORDS.length} unique 4-letter words`);

// ── Build lookup indexes ───────────────────────────────────────────────────
const byL1 = {};    // words[first_letter]
const byL12 = {};   // words[first_two_letters]
const byL123 = {};  // words[first_three_letters]

for (const w of WORDS) {
  const k1 = w[0];
  const k2 = w[0]+w[1];
  const k3 = w[0]+w[1]+w[2];
  if (!byL1[k1])   byL1[k1]   = [];
  if (!byL12[k2])  byL12[k2]  = [];
  if (!byL123[k3]) byL123[k3] = [];
  byL1[k1].push(w);
  byL12[k2].push(w);
  byL123[k3].push(w);
}

// ── Generate all valid 4×4 word squares ───────────────────────────────────
// A word square satisfies: GRID[i][j] === GRID[j][i]
// Given row words w1,w2,w3,w4:
//   w2[0]=w1[1]  w3[0]=w1[2]  w4[0]=w1[3]
//   w3[1]=w2[2]  w4[1]=w2[3]
//   w4[2]=w3[3]
const squares = [];
let checked = 0;

for (const w1 of WORDS) {
  const w2list = byL1[w1[1]] || [];
  for (const w2 of w2list) {
    if (w2 === w1) continue;
    const w3list = byL12[w1[2]+w2[2]] || [];
    for (const w3 of w3list) {
      if (w3 === w1 || w3 === w2) continue;
      const w4list = byL123[w1[3]+w2[3]+w3[3]] || [];
      for (const w4 of w4list) {
        if (w4 === w1 || w4 === w2 || w4 === w3) continue;
        checked++;
        squares.push([w1, w2, w3, w4]);
      }
    }
  }
}

console.log(`Checked ${checked} combinations, found ${squares.length} valid word squares`);

// ── Load existing puzzles ──────────────────────────────────────────────────
const existing = JSON.parse(
  readFileSync(join(__dir, 'noon_puzzles_final.json'), 'utf8')
);
const existingKeys = new Set(existing.map(p => p.words.join(',')));
console.log(`Existing puzzles: ${existing.length}`);

// ── Assign reveal index ────────────────────────────────────────────────────
// Word rank: prefer common words (earlier in our list) as the reveal
const wordRank = new Map(WORDS.map((w, i) => [w, i]));

function bestReveal(words) {
  let best = 0;
  let bestR = wordRank.get(words[0]) ?? 9999;
  for (let i = 1; i < 4; i++) {
    const r = wordRank.get(words[i]) ?? 9999;
    if (r < bestR) { bestR = r; best = i; }
  }
  return best;
}

// ── De-duplicate and build new puzzles ────────────────────────────────────
const seenKeys = new Set(existingKeys);
const newPuzzles = [];

for (const [w1, w2, w3, w4] of squares) {
  const words = [w1, w2, w3, w4];
  const key = words.join(',');
  if (seenKeys.has(key)) continue;
  seenKeys.add(key);
  newPuzzles.push({ words, reveal: bestReveal(words) });
}

console.log(`New unique puzzles generated: ${newPuzzles.length}`);

// ── Shuffle new puzzles for variety ───────────────────────────────────────
for (let i = newPuzzles.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [newPuzzles[i], newPuzzles[j]] = [newPuzzles[j], newPuzzles[i]];
}

// ── Combine: keep existing first, append new ──────────────────────────────
const allPuzzles = [...existing, ...newPuzzles];
console.log(`Total puzzles: ${allPuzzles.length} (covers ${(allPuzzles.length / 365).toFixed(1)} years)`);

// ── Write output ──────────────────────────────────────────────────────────
writeFileSync(
  join(__dir, 'noon_puzzles_final.json'),
  JSON.stringify(allPuzzles, null, 2)
);
console.log('✓ Written to noon_puzzles_final.json');
